### ISSUE TITLE
The plugin omit "..." in commands in steps

### ISSUE THREAD

**Issue by wingyplus** [bitsbeats/drone-tree-config#22]
I found an issue that my drone that install this plugin cannot run the command `go test ./...`. After build got trigger, it will convert go test command into `go test ./`. 

This is the example of test case:

```
kind: pipeline
type: kubernetes
name: default

steps:
- name: vendor
  image: golang:1.14-alpine3.11
  environment:
    CGO_ENABLED: 0
    GO_PRIVATE: "<repo.com>/*"
  commands:
  - apk add --no-cache git
  - go mod vendor

- name: test
  image: golang:1.14-alpine3.11
  environment:
    CGO_ENABLED: 0
  commands:
  - go test ./...
```

The result of my ci is :

![Screen Shot 2563-05-21 at 09 57 59](https://user-images.githubusercontent.com/484530/82518428-956ba880-9b49-11ea-9d32-83d99594b04b.png)
